### ISSUE TITLE
[Bug] AttributeError: module 'pinecone' has no attribute 'GRPCIndex'

### ISSUE THREAD

**Issue by Abe410** [pinecone-io/pinecone-python-client#210] opened 2023-10-04 04:21 UTC
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have pinecone upgraded to v2.2.4, and also installed the GRPC client. 

When I run the following command:

`index = pinecone.GRPCIndex(index_name)`

I get the following error:

`AttributeError: module 'pinecone' has no attribute 'GRPCIndex'`

### Expected Behavior

Previously when using v2.2.2, using the same pipeline worked.

### Steps To Reproduce

Run Pinecone v2.2.4 with GRPC client.

### Environment

```markdown
- OS:
- Python: 3.10.11
- pinecone: 2.2.4
```

**Comment by chostyouwang** [comment] 2023-10-16 07:39
I also encountered the same problem. Did you find a solution?

**Comment by chostyouwang** [comment] 2023-10-16 07:52
I had to uninstall pinecone using:
pip3 uninstall pinecone-client

Then reinstall pinecone with:
pip3 install pinecone-client[grpc]
it seem like ok

**Comment by SID262000** [comment] 2023-11-28 18:04
@Abe410 Feel free to close this issue if the proposed solution by @chostyouwang works as intended, Thanks!

**Closed** 2024-05-03 08:07 UTC
Labels: bug
