### ISSUE TITLE
[Bug] TypeError: __init__() missing 1 required positional argument: 'top_k'

### ISSUE THREAD

**Issue by Chubop** [pinecone-io/pinecone-python-client#171] opened 2023-05-03 17:29 UTC
### Is this a new bug in the Pinecone Python client?

- [X] I believe this is a new bug in the Pinecone Python Client
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When trying to query my existing index, I get an error telling me that I am missing the "top_k" parameter, even though I am not missing it.

### Expected Behavior

Query the Pinecone index 

### Steps To Reproduce

1. In Python 3.8 using PyCharm, attempt to use basic query example.

```
def __init__(self, documents, embedding, model_name: str = "text-davinci-003", namespace: str = "example"):
        self.index = pinecone.Index(namespace)
        ...

def query(self):
        query_response = self.index.query(
            namespace=self.namespace,
            top_k=10,
            include_values=True,
            include_metadata=True,
        )
        return query_response
```

### Relevant log output

```
Traceback (most recent call last):
  File "C:/Users/retai/PycharmProjects/earnings-ai/main.py", line 43, in <module>
    query = Index.index.query()
  File "C:\Users\retai\PycharmProjects\earnings-ai\venv\lib\site-packages\pinecone\core\utils\error_handling.py", line 17, in inner_func
    return func(*args, **kwargs)
  File "C:\Users\retai\PycharmProjects\earnings-ai\venv\lib\site-packages\pinecone\index.py", line 450, in query
    QueryRequest(
  File "C:\Users\retai\PycharmProjects\earnings-ai\venv\lib\site-packages\pinecone\core\client\model_utils.py", line 49, in wrapped_init
    return fn(_self, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'top_k'
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.8
- pinecone: 2.2.1
```

**Comment by SamREye** [comment] 2023-06-20 15:20
I had the same issue.... In my case, the root cause was that I wasn't giving it a search vector.

Put simply: you're missing the 'vector' parameter, you need a non-None search vector. I think that should do it.

**Comment by rjarun8** [comment] 2023-07-01 13:01
Positional arguments are arguments that need to be specified in the correct order or position during a function call. The order in which they are passed matters because that's how they are assigned to the corresponding parameters in the function definition.

**For example, consider the following function:**

```
def greet(name, greeting):
    print(f"{greeting}, {name}!")
```
In this function, name and greeting are positional arguments. When you call this function, you need to provide the arguments in the same order as they are defined:


`greet("Alice", "Hello")  # prints "Hello, Alice!"`

If you switch the order of the arguments, you'll get a different result:


`greet("Hello", "Alice")  # prints "Alice, Hello!"`

In your case, the query method in the Pinecone Python client requires either a vector or an id argument to be provided. These are positional arguments and are used to specify the query vector or the unique ID of the vector to be used as a query vector, respectively.

In your code, you're calling the query method without providing either a vector or an id argument:


```
def query(self):
    query_response = self.index.query(
        namespace=self.namespace,
        top_k=10,
        include_values=True,
        include_metadata=True,
    )
    return query_response
```
Because neither vector nor id is provided, the function is unable to correctly assign the arguments to the parameters, leading to the error. The function is expecting a vector or an id as the first argument, but it's getting namespace instead, which is causing the confusion.

To fix this, you should provide either a vector or an id argument when calling the query method. The order of the arguments should match the order of the parameters in the function definition.

**order of arguments for the query function:**

- self (implicitly passed as the first argument, representing the instance of the class)

- vector (optional): A list of floats representing the vector. Default value is None.

- id (optional): A string representing the ID. Default value is None.

- queries (optional): A list of either QueryVector objects or tuples. Default value is None.

- top_k (optional): An integer representing the number of top results to retrieve. Default value is None.

- namespace (optional): A string representing the namespace. Default value is None.

- filter (optional): A dictionary containing filter criteria. Default value is None.

- include_values (optional): A boolean indicating whether to include values. Default value is None.

- include_metadata (optional): A boolean indicating whether to include metadata. Default value is None.

- sparse_vector (optional): A sparse vector represented either by SparseValues or a dictionary. Default value is None.

- **kwargs (variable length arguments): Additional keyword arguments that can be passed. These arguments are captured as a dictionary.

**Closed** 2024-05-03 08:23 UTC
Labels: bug
